name = "after-dark-suizo"
description = "A robust, elegant dark theme"
license = "MIT"

[extra]


[author]
name = "elsuizo"

[original]
author =  "comfusion"
homepage = "https://git.habd.as/comfusion/after-dark/"
repo = "https://git.habd.as/comfusion/after-dark/"
